name: Reusable - Build Master

on:
  workflow_call:
    inputs:
      imageName:
        required: true
        type: string
      semverFile:
        required: true
        type: string
      testPath:
        required: true
        type: string
      buildStatusPath:
        required: true
        type: string
      pullImages:
        required: false
        type: string
      cachedStages:
        required: false
        type: string
      buildStage:
        required: false
        type: string
      releaseStage:
        required: false
        type: string
      extraBuildArgs:
        required: false
        type: string
      dockerfileDirectory:
        required: false
        type: string
      dockerfileName:
        required: false
        type: string
      ignore-missing-unit-tests:
        required: false
        type: boolean
        description: When to fail if missing unit tests
        default: false
      ecr-region:
        required: false
        type: string
        default: us-east-1

    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
      ecr-registry:
        required: true

    outputs:
      repository:
        description: "The ECR repository"
        value: ${{ jobs.publish-to-ecr.outputs.repository }}
      imageTag:
        description: "The tag of the built image"
        value: ${{ jobs.publish-to-ecr.outputs.imageTag }}

jobs:
  build-and-test:
    name: "Build and Test"
    runs-on: [ self-hosted, ops-pv ]
    outputs:
      imageTag: ${{ steps.build.outputs.imageTag }}
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: ${{ inputs.ecr-region }}

      - name: Login to Amazon ECR for Pre-Pull Images
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        id: build
        uses: pointivo/action-build@v2
        with:
          imageName: ${{ inputs.imageName }}
          semverFile: ${{ inputs.semverFile }}
          cachedStages: ${{ inputs.cachedStages }}
          pullImages: ${{ inputs.pullImages }}
          extraBuildArgs: ${{ inputs.extraBuildArgs }}
          testPath: ${{ inputs.testPath }}
          buildStatusPath: ${{ inputs.buildStatusPath }}
          releaseTag: ${{ inputs.releaseTag }}
          buildStage: ${{ inputs.buildStage }}
          releaseStage: ${{ inputs.releaseStage }}
          dockerfileDirectory: ${{ inputs.dockerfileDirectory }}
          dockerfileName: ${{ inputs.dockerfileName }}

      - name: Upload Unit Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: unit-tests-artifacts
          path: build/artifacts/
          if-no-files-found: warn

  publish-test-results:
    name: "Publish Unit Tests Results"
    needs: build-and-test
    runs-on: ubuntu-latest
    if: success() || failure()
    steps:
      - name: Check ENV
        id: check
        run: echo "ignoreMissing=${{ inputs.ignore-missing-unit-tests }}" >> $GITHUB_OUTPUT

      - name: Download Artifacts
        id: download
        uses: actions/download-artifact@v2
        continue-on-error: ${{ steps.check.outputs.ignoreMissing != '' }}
        with:
          name: unit-tests-artifacts

      - name: Display structure of downloaded files
        run: ls -R

      - name: Publish Unit Test Results
        id: test-results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: steps.download.outcome == 'success'
        with:
          root_log_level: DEBUG
          log_level: DEBUG
          files: |
            *.xml
            ./**/*.xml
            !**_cov.xml

  publish-to-ecr:
    name: "Publish Image to ECR"
    needs: build-and-test
    runs-on: [ self-hosted, ops-pv ]
    if: success()
    outputs:
      repository: ${{ steps.push.outputs.repository }}
      imageTag: ${{ steps.push.outputs.imageTag }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: ${{ inputs.ecr-region }}

      - name: Tag and push image to Amazon ECR
        id: push
        env:
          REGISTRY: ${{ secrets.ecr-registry }}
          REPOSITORY: ${{ inputs.imageName }}
          IMAGE_TAG: ${{ needs.build-and-test.outputs.imageTag }}
        run: |
          echo REGISTRY=$REGISTRY
          echo IMAGE_TAG=$IMAGE_TAG
          echo REPOSITORY=$REPOSITORY
          echo IMAGE_TAG=$IMAGE_TAG
          BRANCH=${GITHUB_REF#refs/heads/}
          echo BRANCH=$BRANCH
          echo "repository=$REPOSITORY" >> $GITHUB_OUTPUT
          echo "imageTag=$IMAGE_TAG" >> $GITHUB_OUTPUT

          # Move tag
          docker tag $REPOSITORY:$IMAGE_TAG $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker tag $REGISTRY/$REPOSITORY:$IMAGE_TAG $REGISTRY/$REPOSITORY:$BRANCH
          
          # Publish to ECR
          
          aws ecr get-login-password --region ${{ inputs.ecr-region }} | 
            docker login --username AWS --password-stdin ${{ secrets.ecr-registry }}
          
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          
          aws ecr get-login-password --region ${{ inputs.ecr-region }} | 
            docker login --username AWS --password-stdin ${{ secrets.ecr-registry }}
          
          docker push $REGISTRY/$REPOSITORY:$BRANCH

  cleanup:
    name: "Cleanup docker resources"
    needs: [ publish-to-ecr, build-and-test ]
    runs-on: [ self-hosted, ops-pv ]
    if: success() || failure()

    steps:
      - name: Cleanup
        uses: pointivo/action-cleanup@master
        env:
          IMAGE_NAME: ${{ inputs.imageName }}
          IMAGE_TAG: ${{ needs.build-and-test.outputs.imageTag }}

  slack-notification:
    name: Slack Notification
    needs: [ build-and-test ]
    runs-on: ubuntu-latest
    steps:
      - name: Slack workflow notification pix4d-gui-01sdk-build
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        if: ${{ env.SLACK_WEBHOOK_URL ~= '' }}
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": "inputs.imageName for <${{github.ref_name}}> build status: ${{ needs.call.status }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ inputs.imageName }} build for <${{github.ref_name}}> was: ${{ needs.call.result }}\n PR or Commit:[Link](${{ github.event.pull_request.html_url || github.event.head_commit.url }}) by: ${{ github.event.pull_request.user.login || github.actor }}"
                  }
                }
              ]
            }
