name: Reusable - Build Master and Check

on:
  workflow_call:
    inputs:
      imageName:
        required: true
        type: string
      semverFile:
        required: true
        type: string
      testPath:
        required: true
        type: string
      buildStatusPath:
        required: true
        type: string
      pullImages:
        required: false
        type: string
      cachedStages:
        required: false
        type: string
      buildStage:
        required: false
        type: string
      releaseStage:
        required: false
        type: string
      extraBuildArgs:
        required: false
        type: string
      dockerfileDirectory:
        required: false
        type: string
      dockerfileName:
        required: false
        type: string
      ignore-missing-unit-tests:
        required: false
        type: boolean
        description: When to fail if missing unit tests
        default: false
      ecr-region:
        required: false
        type: string
        default: us-east-1
      runner:
        required: false
        type: string
        default: ops-pv-test

    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
      ecr-registry:
        required: true
      slack-webhook-url:
        required: false

jobs:
  build-and-test:
    name: "Build and Test"
    runs-on: ${{ inputs.runner }}
    outputs:
      imageTag: ${{ steps.build.outputs.imageTag }}
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: ${{ inputs.ecr-region }}

      - name: Login to Amazon ECR for Pre-Pull Images
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        id: build
        uses: pointivo/action-build@v2
        with:
          imageName: ${{ inputs.imageName }}
          semverFile: ${{ inputs.semverFile }}
          cachedStages: ${{ inputs.cachedStages }}
          pullImages: ${{ inputs.pullImages }}
          extraBuildArgs: ${{ inputs.extraBuildArgs }}
          testPath: ${{ inputs.testPath }}
          buildStatusPath: ${{ inputs.buildStatusPath }}
          releaseTag: ${{ inputs.releaseTag }}
          buildStage: ${{ inputs.buildStage }}
          releaseStage: ${{ inputs.releaseStage }}
          dockerfileDirectory: ${{ inputs.dockerfileDirectory }}
          dockerfileName: ${{ inputs.dockerfileName }}

      - name: Upload Unit Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-tests-artifacts
          path: build/artifacts/
          if-no-files-found: warn
          overwrite: 'true'

  publish-test-results:
    name: "Publish Unit Tests Results"
    needs: build-and-test
    runs-on: ubuntu-latest
    if: success() || failure()
    steps:
      - name: Check ENV
        id: check
        run: echo "ignoreMissing=${{ inputs.ignore-missing-unit-tests }}" >> $GITHUB_OUTPUT

      - name: Download Artifacts
        id: download
        uses: actions/download-artifact@v4
        continue-on-error: ${{ steps.check.outputs.ignoreMissing != '' }}
        with:
          name: unit-tests-artifacts

      - name: Display structure of downloaded files
        run: ls -R

      - name: Publish Unit Test Results
        id: test-results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: steps.download.outcome == 'success'
        with:
          action_fail: true
          files: |
            *.xml
            ./**/*.xml
            !**_cov.xml

  cleanup:
    name: "Cleanup docker resources"
    needs: [ build-and-test ]
    runs-on: ${{ inputs.runner }}
    if: success() || failure()

    steps:
      - name: Cleanup
        uses: pointivo/action-cleanup@master
        env:
          IMAGE_NAME: ${{ inputs.imageName }}
          IMAGE_TAG: ${{ needs.build-and-test.outputs.imageTag }}

  slack-notification:
    name: "Slack Notification"
    needs: [ build-and-test ]
    if: always()
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Slack workflow notification
        uses: slackapi/slack-github-action@v1.25.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.slack-webhook-url }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        if: env.SLACK_WEBHOOK_URL != ''
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ inputs.imageName }} build-check status for branch <${{github.head_ref}}> was: ${{ needs.build-and-test.result }} (<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} | Open>)"
                  }
                }
              ]
            }
