name: Reusable - Deploy Release

on:
  workflow_call:
    inputs:
      imageName:
        required: true
        type: string
        default: false
      # from create-release-build
      imageTag:
        required: true
        type: string
        default: false
      # from create-release-build
      repository:
        required: true
        type: string
        default: false
      eks-region:
        required: false
        type: string
        default: us-east-1
      k8s-deployment-namespace:
        required: false
        type: string
        default: qa

    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
      ecr-registry:
        required: true
      eks-qa-cluster:
        required: true

jobs:
  deploy-to-k8s-qa:
    name: "Deploy to K8s-QA"
    runs-on: ubuntu-latest
    steps:
      - name: Get Variables
        env:
          REGISTRY: ${{ secrets.ecr-registry }}
          REPOSITORY: ${{ inputs.repository }}
          POD_NAME: ${{ inputs.imageName }}
          IMAGE_TAG: ${{ inputs.imageTag }}
        run: |
          echo REGISTRY=$REGISTRY
          echo REPOSITORY=$REPOSITORY
          echo IMAGE_TAG=$IMAGE_TAG
          IMAGE_URL="${REGISTRY}/${REPOSITORY}:${IMAGE_TAG}"
          echo "IMAGE_URL=${IMAGE_URL}"
          echo "IMAGE_URL=${IMAGE_URL}" >> $GITHUB_ENV
          echo "POD_NAME=${POD_NAME}" >> $GITHUB_ENV

      - name: Promote to QA
        uses: ianbelcher/eks-kubectl-action@master
        if: inputs.imageName != 'rabbit-pod-autoscaler'
        with:
          aws_access_key_id: ${{ secrets.aws-access-key-id }}
          aws_secret_access_key: ${{ secrets.aws-secret-access-key }}
          aws_region: ${{ inputs.eks-region }}
          cluster_name: ${{ secrets.eks-qa-cluster }}
          args: -n ${{ inputs.k8s-deployment-namespace }} set image deployment/${{ env.POD_NAME }} ${{ env.POD_NAME }}=${{ env.IMAGE_URL }}

      - name: Monitor Rollout
        uses: ianbelcher/eks-kubectl-action@master
        if: inputs.imageName != 'rabbit-pod-autoscaler'
        with:
          aws_access_key_id: ${{ secrets.aws-access-key-id }}
          aws_secret_access_key: ${{ secrets.aws-secret-access-key }}
          aws_region: ${{ inputs.eks-region }}
          cluster_name: ${{ secrets.eks-qa-cluster }}
          args: -n ${{ inputs.k8s-deployment-namespace }} rollout status deployment/${{ env.POD_NAME }} --timeout=10m
