name: Reusable - Create Release

on:
  workflow_call:
    inputs:
      releaseVersion:
        required: false
        type: string
      imageName:
        required: true
        type: string
      semverFile:
        required: true
        type: string
      cachedStages:
        required: true
        type: string
      pullImages:
        required: true
        type: string
      extraBuildArgs:
        required: true
        type: string
      testPath:
        required: true
        type: string
      buildStatusPath:
        required: true
        type: string
      changeLogFile:
        required: true
        type: string
      # Not Required
      skipPromotion:
        required: false
        type: boolean
        default: false
      buildStage:
        required: false
        type: string
      releaseStage:
        required: false
        type: string
      releaseTag:
        required: false
        type: string
        default: release
      dockerfileDirectory:
        required: false
        type: string
      dockerfileName:
        required: false
        type: string
      ecr-region:
        required: false
        type: string
        default: us-east-1
      eks-region:
        required: false
        type: string
        default: us-east-1


    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
      ecr-registry:
        required: true
      github-token:
        required: true
      eks-master-cluster:
        required: true
      eks-qa-cluster:
        required: true


jobs:
  create-new-release:
    name: "Create a new release"
    runs-on: ubuntu-latest
    outputs:
      releaseVersion: ${{ steps.version.outputs.releaseVersion }}
      releaseCommit: ${{ steps.make-commit.outputs.releaseCommit }}
    container:
      image: ghcr.io/pointivo/devops-docker
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.repository.default_branch }}
          fetch-depth: 1

      - name: Set Release Version
        if: inputs.releaseVersion != ''
        env:
          SEMVER_FILE: ${{ inputs.semverFile }}
        run: |
          bash version.sh -s ${{ inputs.releaseVersion }}

      - name: Get Release Version
        id: version
        env:
          SEMVER_FILE: ${{ inputs.semverFile }}
        run: |
          RELEASE_VERSION=$(bash version.sh -g)
          echo "Release version will be ${RELEASE_VERSION}"
          echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_ENV
          RELEASE_SHORT=$(echo "${RELEASE_VERSION}" | awk 'BEGIN {FS=".";OFS="."} { print $1,$2 }')
          echo "RELEASE_SHORT=${RELEASE_SHORT}" >> $GITHUB_ENV
          echo "::set-output name=releaseVersion::$RELEASE_VERSION"

      - name: Update changelog
        uses: thomaseizinger/keep-a-changelog-new-release@1.3.0
        with:
          version: ${{ env.RELEASE_VERSION }}
          changelogPath: ${{ inputs.changelogFile }}
          tag: ${{ env.RELEASE_VERSION }}-${{ inputs.imageName }}

      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub actions"
          git config user.email noreply@github.com

      - name: Commit changelog and bump Master
        id: make-commit
        env:
          SEMVER_FILE: ${{ inputs.semverFile }}
        run: |
          git add ${{ inputs.changelogFile }}
          git add $(bash version.sh -p)
          git commit --message "Create release - ${{ inputs.imageName }} v${{ env.RELEASE_VERSION }}"
          echo "::set-output name=releaseCommit::$(git rev-parse HEAD)"
          
          # Bump minor version
          bash version.sh -b minor
          git add $(bash version.sh -p)
          git commit --message "Bump Minor version after Release (v${RELEASED_VERSION})"
          
          # Single push
          git push origin ${{ github.event.repository.default_branch }}

      - name: Extract Changelog
        run: |
          sed -n '/## \[${{ env.RELEASE_VERSION }}\]/,/## \[/p' ${{ inputs.changelogFile }} | tail -n +2 | sed '$d' > CHANGELOG_RELEASE.md

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}
        with:
          commitish: ${{ steps.make-commit.outputs.releaseCommit }}
          tag_name: ${{ env.RELEASE_VERSION }}-${{ inputs.imageName }}
          release_name: v${{ env.RELEASE_VERSION }} - ${{ inputs.imageName }}
          draft: false
          prerelease: false
          body_path: CHANGELOG_RELEASE.md

      - name: Create release branch from tag
        run: |
          git fetch
          git checkout -b ${{ inputs.imageName }}/release_${{ env.RELEASE_SHORT }} ${{ env.RELEASE_VERSION }}-${{ inputs.imageName }}
          git push origin ${{ inputs.imageName }}/release_${{ env.RELEASE_SHORT }}

  build-and-test:
    name: "Prepare build"
    needs: create-new-release
    runs-on: [ self-hosted ]
    outputs:
      imageTag: ${{ steps.build.outputs.imageTag }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ needs.create-new-release.outputs.releaseCommit }}
          lfs: true

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Set Release Version
        env:
          SEMVER_FILE: ${{ inputs.semverFile }}
        run: |
          bash version.sh -s ${{ needs.create-new-release.outputs.releaseVersion }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: ${{ inputs.ecr-region }}

      - name: Login to Amazon ECR for Pre-Pull Images
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        id: build
        uses: pointivo/action-build@v2
        with:
          imageName: ${{ inputs.imageName }}
          semverFile: ${{ inputs.semverFile }}
          cachedStages: ${{ inputs.cachedStages }}
          pullImages: ${{ inputs.pullImages }}
          extraBuildArgs: ${{ inputs.extraBuildArgs }}
          testPath: ${{ inputs.testPath }}
          buildStatusPath: ${{ inputs.buildStatusPath }}
          releaseTag: ${{ inputs.releaseTag }}
          buildStage: ${{ inputs.buildStage }}
          releaseStage: ${{ inputs.releaseStage }}
          dockerfileDirectory: ${{ inputs.dockerfileDirectory }}
          dockerfileName: ${{ inputs.dockerfileName }}

      - name: Upload Unit Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: unit-tests-artifacts
          path: build/artifacts/
          if-no-files-found: warn

  publish-test-results:
    name: "Publish Unit Tests Results"
    needs: build-and-test
    runs-on: ubuntu-latest
    if: success() || failure()

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: unit-tests-artifacts

      - name: Display structure of downloaded files
        run: ls -R

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: |
            *.xml
            ./**/*.xml
            !**_cov.xml

  publish-to-ecr:
    name: "Publish Image to ECR"
    needs: build-and-test
    runs-on: [ self-hosted ]
    if: success()
    outputs:
      repository: ${{ steps.push.outputs.repository }}
      imageTag: ${{ steps.push.outputs.imageTag }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: ${{ inputs.ecr-region }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Tag and push image to Amazon ECR
        id: push
        env:
          REGISTRY: ${{ secrets.ecr-registry }}
          REPOSITORY: ${{ inputs.imageName }}
          IMAGE_TAG: ${{ needs.build-and-test.outputs.imageTag }}
        run: |
          echo "::set-output name=imageTag::$IMAGE_TAG"

          # Publish to ECR
          docker tag $REPOSITORY:$IMAGE_TAG $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

          # Move tags
          docker tag $REGISTRY/$REPOSITORY:$IMAGE_TAG $REGISTRY/$REPOSITORY:master
          docker push $REGISTRY/$REPOSITORY:master
          docker rmi $REGISTRY/$REPOSITORY:master
          
          docker tag $REGISTRY/$REPOSITORY:$IMAGE_TAG $REGISTRY/$REPOSITORY:qa
          docker push $REGISTRY/$REPOSITORY:qa
          docker rmi $REGISTRY/$REPOSITORY:qa
          
          docker rmi $REPOSITORY:$IMAGE_TAG || true
          docker rmi --force $REGISTRY/$REPOSITORY:$IMAGE_TAG

  deploy-to-k8s-qa:
    name: "Deploy to K8s-QA"
    needs: [ publish-to-ecr, create-new-release, deploy-to-k8s-master ]
    runs-on: ubuntu-latest
    if: success() && (!inputs.skipPromotion || inputs.skipPromotion == 'false')
    steps:
      - name: Get Variables
        env:
          REGISTRY: ${{ secrets.ecr-registry }}
          REPOSITORY: ${{ inputs.imageName }}
          POD_NAME: ${{ inputs.imageName }}
          IMAGE_TAG: ${{ needs.publish-to-ecr.outputs.imageTag }}
        run: |
          echo REGISTRY=$REGISTRY
          echo REPOSITORY=$REPOSITORY
          echo IMAGE_TAG=$IMAGE_TAG
          IMAGE_URL="${REGISTRY}/${REPOSITORY}:${IMAGE_TAG}"
          echo "IMAGE_URL=${IMAGE_URL}"
          echo "IMAGE_URL=${IMAGE_URL}" >> $GITHUB_ENV
          echo "POD_NAME=${POD_NAME}" >> $GITHUB_ENV

      - name: Promote to QA
        uses: ianbelcher/eks-kubectl-action@master
        with:
          aws_access_key_id: ${{ secrets.aws-access-key-id }}
          aws_secret_access_key: ${{ secrets.aws-secret-access-key }}
          aws_region: ${{ inputs.eks-region }}
          cluster_name: ${{ secrets.eks-qa-cluster }}
          args: -n qa set image deployment/${{ env.POD_NAME }} ${{ env.POD_NAME }}=${{ env.IMAGE_URL }}

      - name: Monitor Rollout
        uses: ianbelcher/eks-kubectl-action@master
        with:
          aws_access_key_id: ${{ secrets.aws-access-key-id }}
          aws_secret_access_key: ${{ secrets.aws-secret-access-key }}
          aws_region: ${{ inputs.eks-region }}
          cluster_name: ${{ secrets.eks-qa-cluster }}
          args: -n qa rollout status deployment/${{ env.POD_NAME }} --timeout=10m

  cleanup:
    name: "Cleanup docker resources"
    needs: [publish-to-ecr, build-and-test]
    runs-on: [ self-hosted ]
    if: success() || failure()

    steps:
      - name: Cleanup
        uses: pointivo/action-cleanup@v1
        env:
          IMAGE_NAME: ${{ inputs.imageName }}
          IMAGE_TAG: ${{ needs.build-and-test.outputs.imageTag }}
