name: Reusable - Shortcut Comment
on:
  workflow_call:
    inputs:
      storyId: # 12345 or sc-12345
        required: true
        type: string
      comment:
        required: true
        type: string
      authorId:
        required: false
        type: string
        # ops@pointivo.com
        default: 67917173-e45e-4632-a07f-a1f3e7116878
    secrets:
      shortcut-api-token:
        required: true
jobs:
  shortcut-comment:
    name: "Shortcut Comment"
    runs-on: [ self-hosted, ops-pv ]
    steps:
      - run: |
          normalized_story_id=$(echo "${{ inputs.storyId }}" | sed 's/\(sc-\)\?\([0-9]\+\)/\2/g' )
          text=$(echo '${{ toJSON(inputs.comment) }}' | sed 's/\\\\n/\\n/g' )
          curl -X POST \
          -H "Content-Type: application/json" \
          -H "Shortcut-Token: ${{ secrets.shortcut-api-token }}" \
          -d "{ \"author_id\": \"${{ inputs.authorId }}\", \"text\": ${text} }" \
          -L "https://api.app.shortcut.com/api/v3/stories/${normalized_story_id}/comments"
